// document.writeln("    <script src=\'js/jquery-3.1.1.min.js\'></script>");
// document.writeln("    <script src=\'js/jquery.flexslider-min.js\'></script>");
// document.writeln("    <script src=\'js/index.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/public.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/index.css\'>");
document.writeln("    <div class=\'footer\'>");
document.writeln("        <div class=\'footer_main\'>");
document.writeln("            <div>");
document.writeln("                <span><a href=\'\'>首页</a></span>");
document.writeln("                <span>|</span>");
document.writeln("                <span><a href=\'\'>公司简介</a></span>");
document.writeln("                <span>|</span>");
document.writeln("                <span><a href=\'\'>访客留言</a></span>");
document.writeln("                <span>|</span>");
document.writeln("                <span><a href=\'\'>友情链接</a></span>");
document.writeln("            </div>");
document.writeln("            <div>天秀公司</div>");
document.writeln("            <div>大神制作,版权所有 粤ICP备15007584</div>");
document.writeln("        </div>");
document.writeln("    </div>   ");