// document.writeln("<!DOCTYPE html>");
// document.writeln("<html lang=\'en\'>");
// document.writeln("<head>");



// document.writeln("    <script src=\'js/jquery-3.1.1.min.js\'></script>");

// document.writeln("    <script src=\'js/index.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/public.css\'>");


document.writeln("    <link rel=\'stylesheet\' href=\'css/index.css\'>");
// document.writeln("</head>");
// document.writeln("<body>");
document.writeln("    <div class=\'header fixed\'>");
document.writeln("        <div class=\'top\'>");
document.writeln("            <div class=\'top_main\'>");
document.writeln("                <div class=\'logo\'>");
document.writeln("                    <a href=\'index.html\'>");
document.writeln("                        <img src=\'images/logo.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'telephone\'>");
document.writeln("                    <a href=\'javascript:void(0)\' onclick=\'SetHome(window.location)\'>设为首页</a>");
document.writeln("                    |");
document.writeln("                    <a href=\'javascript:void(0)\' onclick=\'AddFavorite(window.location,document.title)\'>加入收藏</a>");
document.writeln("                    <a href=\'\'>");
document.writeln("                        <img src=\'images/telephone.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'clear\'></div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'head clearfix\'>");
document.writeln("            <ul class=\'nav\'>");
document.writeln("                <li class=\'li01\'>");
document.writeln("                    <a href=\'index.html\'>首页</a>");
document.writeln("                </li>");

document.writeln("                <li id=\'erji5\'>");
document.writeln("                    <a class=\'li02\' href=\'news.html\'>资讯中心</a>");
document.writeln("                    <div class=\'erji noDisplay\' id=\'erji55\'>");
document.writeln("                        <p><a href=\'1\'>1</a></p>");
document.writeln("                        <p><a href=\'2\'>1</a></p>");
document.writeln("                        <p><a href=\'3\'>1</a></p>");
document.writeln("                    </div>");
document.writeln("                </li>");

document.writeln("                <li id=\'erji1\'>");
document.writeln("                    <a class=\'li02\' href=\'product.html\'>公司产品</a>");
document.writeln("                    <div class=\'erji noDisplay\' id=\'erji11\'>");
document.writeln("                        <p><a href=\'\'>1</a></p>");
document.writeln("                        <p><a href=\'\'>1</a></p>");
document.writeln("                        <p><a href=\'\'>1</a></p>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li id=\'erji2\'>");
document.writeln("                    <a class=\'li02\' href=\'successCase.html\'>成功案例</a>");
document.writeln("                    <div class=\'erji noDisplay\' id=\'erji22\'>");
document.writeln("                        <p><a href=\'\'>1</a></p>");
document.writeln("                        <p><a href=\'\'>1</a></p>");
document.writeln("                        <p><a href=\'\'>1</a></p>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li id=\'erji3\'>");
document.writeln("                    <a class=\'li02\' href=\'introduce.html\'>公司信息</a>");
document.writeln("                    <div class=\'erji noDisplay\' id=\'erji33\'>");
document.writeln("                        <p><a href=\'introduce.html\'>公司简介</a></p>");
document.writeln("                        <p><a href=\'\'>企业文化</a></p>");
document.writeln("                        <p><a href=\'\'>招聘信息</a></p>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li id=\'erji4\'>");
document.writeln("                    <a class=\'li02\' href=\'contactWe.html\'>联系我们</a>");
document.writeln("                    <div class=\'erji noDisplay\' id=\'erji44\'>");
document.writeln("                        <p><a href=\'contactWe.html\'>联系方式</a></p>");
document.writeln("                        <p><a href=\'\'>访客留言</a></p>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>  ");
document.writeln("<script>");
document.writeln("        function AddFavorite(sURL, sTitle) {");
document.writeln("        sURL = encodeURI(sURL);");
document.writeln("        try {");
document.writeln("            window.external.addFavorite(sURL, sTitle);");
document.writeln("        } catch (e) {");
document.writeln("            try {");
document.writeln("                window.sidebar.addPanel(sTitle, sURL, \'\');");
document.writeln("            } catch (e) {");
document.writeln("                alert(\'加入收藏失败，请使用Ctrl+D进行添加,或手动在浏览器里进行设置.\');");
document.writeln("            }");
document.writeln("        }");
document.writeln("    }");
document.writeln("    //设为首页");
document.writeln("    function SetHome(url) {");
document.writeln("        if (document.all) {");
document.writeln("            document.body.style.behavior = \'url(#default#homepage)\';");
document.writeln("            document.body.setHomePage(url);");
document.writeln("        } else {");
document.writeln("            alert(\'您好,您的浏览器不支持自动设置页面为首页功能,请您手动在浏览器里设置该页面为首页!\');");
document.writeln("        }");
document.writeln("    }");
document.writeln("    //导航栏事件");
document.writeln("    $(\'.li02\').each(function(index){");
document.writeln("        var liNode = $(this);");
document.writeln("        $(this).mouseover(function(){");
document.writeln("            // $(\'.erji\').removeClass(\'noDisplay\');");
document.writeln("            $(\'.nav li div\').eq(index).addClass(\'display\');            ");
document.writeln("        })       ");
document.writeln("    });");
document.writeln("    $(\'#erji1\').mouseleave(function(index){");
document.writeln("        $(\'#erji11\').removeClass(\'display\');");
document.writeln("    });   ");
document.writeln("    $(\'#erji2\').mouseleave(function(index){");
document.writeln("        $(\'#erji22\').removeClass(\'display\');            ");
document.writeln("    });");
document.writeln("    $(\'#erji3\').mouseleave(function(index){");
document.writeln("        $(\'#erji33\').removeClass(\'display\');            ");
document.writeln("    });");
document.writeln("    $(\'#erji4\').mouseleave(function(index){");
document.writeln("        $(\'#erji44\').removeClass(\'display\');            ");
document.writeln("    });");
document.writeln("    $(\'#erji5\').mouseleave(function(index){");
document.writeln("        $(\'#erji55\').removeClass(\'display\');            ");
document.writeln("    });");
document.writeln("    </script>");