document.writeln("    <link rel=\'stylesheet\' href=\'css/public.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/left.css\'>");
document.writeln("    <div class=\'sub_mltcon\'>");
document.writeln("        <dl>");
document.writeln("            <dt>");
document.writeln("                <div class=\'sub_leftna\'>最新资讯</div>");
document.writeln("                <div class=\'sub_leftmore\'>");
document.writeln("                    <a href=\'\'>MORE</a>");
document.writeln("                </div>");
document.writeln("            </dt>");
document.writeln("            <dd>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>新闻1</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>新闻1</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>新闻1</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>新闻1</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>新闻1</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>新闻1</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </dd>");
document.writeln("        </dl>");
document.writeln("        <br>");
document.writeln("        <dl>");
document.writeln("            <dt>");
document.writeln("                <div class=\'sub_leftna\'>联系方式</div>");
document.writeln("            </dt>");
document.writeln("            <dd>");
document.writeln("                <div style=\'font-size:13px;line-height: 18px;padding:5px 10px\'>");
document.writeln("                    公司地址:");
document.writeln("                    <br>");
document.writeln("                    12ahahhfhaafhas");
document.writeln("                    <br>");
document.writeln("                    邮政编码:10086");
document.writeln("                    <br>");
document.writeln("                    公司电话:110");
document.writeln("                    <br>");
document.writeln("                    公司邮箱:119");
document.writeln("                    <br>");
document.writeln("                </div>");
document.writeln("            </dd>");
document.writeln("        </dl>");
document.writeln("    </div>");